import type { OmanLocationCandidateDimension } from '@/config/geo/location-threshold-policy';
import type { OmanGeoRouteEntity } from '@/config/geo/route-contract';

export type OmanLocationCandidatePromotionChecklistStatus = 'contract-only' | 'blocked' | 'ready-for-review' | 'approved';

export type OmanLocationCandidatePromotionChecklistKey =
  | 'canonical-parent-hierarchy'
  | 'candidate-path'
  | 'threshold-policy'
  | 'provider-counts'
  | 'approved-evidence'
  | 'source-refs'
  | 'readiness-gates'
  | 'human-review'
  | 'promotion-pr'
  | 'blocked-reasons'
  | 'noindex-default'
  | 'sitemap-disabled'
  | 'jsonld-disabled'
  | 'internal-links-disabled';

export type OmanLocationCandidatePromotionChecklistItem = {
  key: OmanLocationCandidatePromotionChecklistKey;
  required: true;
  currentlySatisfied: false;
};

export type OmanLocationCandidatePromotionChecklistPolicy = {
  entity: OmanGeoRouteEntity;
  dimension: OmanLocationCandidateDimension;
  checklist: readonly OmanLocationCandidatePromotionChecklistItem[];
  promotionAllowed: false;
};

export const OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_CONTRACT_VERSION = 'v1' as const;

export const OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS: readonly OmanLocationCandidatePromotionChecklistItem[] = [
  { key: 'canonical-parent-hierarchy', required: true, currentlySatisfied: false },
  { key: 'candidate-path', required: true, currentlySatisfied: false },
  { key: 'threshold-policy', required: true, currentlySatisfied: false },
  { key: 'provider-counts', required: true, currentlySatisfied: false },
  { key: 'approved-evidence', required: true, currentlySatisfied: false },
  { key: 'source-refs', required: true, currentlySatisfied: false },
  { key: 'readiness-gates', required: true, currentlySatisfied: false },
  { key: 'human-review', required: true, currentlySatisfied: false },
  { key: 'promotion-pr', required: true, currentlySatisfied: false },
  { key: 'blocked-reasons', required: true, currentlySatisfied: false },
  { key: 'noindex-default', required: true, currentlySatisfied: false },
  { key: 'sitemap-disabled', required: true, currentlySatisfied: false },
  { key: 'jsonld-disabled', required: true, currentlySatisfied: false },
  { key: 'internal-links-disabled', required: true, currentlySatisfied: false },
] as const;

export const OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_POLICIES: readonly OmanLocationCandidatePromotionChecklistPolicy[] = [
  { entity: 'governorate', dimension: 'category', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'governorate', dimension: 'service', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'governorate', dimension: 'specialty', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'wilayat', dimension: 'category', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'wilayat', dimension: 'service', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'wilayat', dimension: 'specialty', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'area', dimension: 'category', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'area', dimension: 'service', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
  { entity: 'area', dimension: 'specialty', checklist: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_ITEMS, promotionAllowed: false },
] as const;

export const OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_CONTRACT = {
  version: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_CONTRACT_VERSION,
  status: 'contract-only' as OmanLocationCandidatePromotionChecklistStatus,
  policies: OMAN_LOCATION_CANDIDATE_PROMOTION_CHECKLIST_POLICIES,
  promotionAllowedByDefault: false,
  reviewAllowedByDefault: false,
  noindexRequiredByDefault: true,
  sitemapAllowedByDefault: false,
  jsonLdAllowedByDefault: false,
  internalLinksAllowedByDefault: false,
  databaseAccessAllowed: false,
  routeCreationAllowed: false,
  runtimePromotionAllowed: false,
  nonGoals: [
    'No candidate promotion is enabled by this contract.',
    'No candidate review workflow is enabled by this contract.',
    'No route is added by this contract.',
    'No sitemap inclusion is allowed by this contract.',
    'No JSON-LD is generated by this contract.',
    'No internal SEO links are enabled by this contract.',
    'No database access is added by this contract.',
  ],
} as const;
