import type { EntityType } from './types';

export const taxonomyEntityTypes = [
  { slug: 'hospital', labelEn: 'Hospital', labelAr: 'مستشفى', descriptionEn: 'Licensed hospital provider entity.', descriptionAr: 'منشأة مستشفى مرخصة لتقديم الرعاية الصحية.', primaryVerticalSlug: 'hospitals', secondaryVerticalSlugs: ['medical'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'high', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'high', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'clinic', labelEn: 'Clinic', labelAr: 'عيادة', descriptionEn: 'Licensed outpatient clinic entity.', descriptionAr: 'منشأة عيادة خارجية مرخصة.', primaryVerticalSlug: 'clinics', secondaryVerticalSlugs: ['medical'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'doctor-profile', labelEn: 'Doctor Profile', labelAr: 'ملف طبيب', descriptionEn: 'Individual licensed doctor profile.', descriptionAr: 'ملف لطبيب فرد مرخص.', primaryVerticalSlug: 'doctors', secondaryVerticalSlugs: ['medical'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'dental-clinic', labelEn: 'Dental Clinic', labelAr: 'عيادة أسنان', descriptionEn: 'Licensed dental clinic entity.', descriptionAr: 'منشأة عيادة أسنان مرخصة.', primaryVerticalSlug: 'dental', secondaryVerticalSlugs: ['medical'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: true, isCommercialLifestyle: false },
  { slug: 'laboratory-center', labelEn: 'Laboratory Center', labelAr: 'مركز مختبرات', descriptionEn: 'Medical laboratory provider entity.', descriptionAr: 'منشأة مختبرات طبية مرخصة.', primaryVerticalSlug: 'laboratory', secondaryVerticalSlugs: ['diagnostics'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'imaging-center', labelEn: 'Imaging Center', labelAr: 'مركز تصوير طبي', descriptionEn: 'Medical imaging provider entity.', descriptionAr: 'منشأة تقدم خدمات التصوير الطبي.', primaryVerticalSlug: 'imaging', secondaryVerticalSlugs: ['diagnostics'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'ivf-center', labelEn: 'IVF Center', labelAr: 'مركز أطفال الأنابيب', descriptionEn: 'Fertility and IVF center entity.', descriptionAr: 'مركز متخصص في الخصوبة وأطفال الأنابيب.', primaryVerticalSlug: 'ivf-fertility', secondaryVerticalSlugs: ['women-health'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'high', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'high', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'fertility-clinic', labelEn: 'Fertility Clinic', labelAr: 'عيادة خصوبة', descriptionEn: 'Fertility clinic provider entity.', descriptionAr: 'عيادة تقدم خدمات الخصوبة وطب الإنجاب.', primaryVerticalSlug: 'ivf-fertility', secondaryVerticalSlugs: ['women-health'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'high', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'high', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'physiotherapy-center', labelEn: 'Physiotherapy Center', labelAr: 'مركز علاج طبيعي', descriptionEn: 'Physiotherapy provider entity.', descriptionAr: 'مركز يقدم خدمات العلاج الطبيعي.', primaryVerticalSlug: 'physiotherapy-rehabilitation', secondaryVerticalSlugs: ['medical'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'rehabilitation-center', labelEn: 'Rehabilitation Center', labelAr: 'مركز إعادة تأهيل', descriptionEn: 'Rehabilitation provider entity.', descriptionAr: 'مركز يقدم خدمات إعادة التأهيل.', primaryVerticalSlug: 'physiotherapy-rehabilitation', secondaryVerticalSlugs: ['medical'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'counseling-center', labelEn: 'Counseling Center', labelAr: 'مركز استشارات نفسية', descriptionEn: 'Psychology and counseling provider entity.', descriptionAr: 'مركز يقدم خدمات نفسية واستشارات مرخصة.', primaryVerticalSlug: 'psychology-counseling', secondaryVerticalSlugs: ['mental-health'], requiresLicense: 'required', requiresMedicalReview: 'required_before_index', medicalRiskLevel: 'medium', isHumanHealthcare: true, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: true, isDental: false, isCommercialLifestyle: false },
  { slug: 'pet-clinic-shop-hybrid', labelEn: 'Pet Clinic Shop Hybrid', labelAr: 'عيادة ومتجر حيوانات أليفة', descriptionEn: 'Pet clinic with related pet retail activity.', descriptionAr: 'عيادة حيوانات أليفة مع نشاط متجر مرتبط بها.', primaryVerticalSlug: 'pet-clinics', secondaryVerticalSlugs: ['pet-shops'], requiresLicense: 'required', requiresMedicalReview: 'recommended', medicalRiskLevel: 'low', isHumanHealthcare: false, publicLaunchPhase: 'core', topicalRisk: 'medium', isMedical: false, isDental: false, isCommercialLifestyle: true }
] as const satisfies readonly EntityType[];
