import type { Specialty } from './types';

export const taxonomySpecialties = [
  { slug: 'general-medicine', labelEn: 'General Medicine', labelAr: 'الطب العام', descriptionEn: 'General medical care specialty.', descriptionAr: 'تخصص الرعاية الطبية العامة.', verticalSlugs: ['medical', 'clinics'], relatedEntityTypeSlugs: ['clinic', 'doctor-profile'], isMentalHealth: false },
  { slug: 'obstetrics-gynecology', labelEn: 'Obstetrics Gynecology', labelAr: 'النساء والولادة', descriptionEn: 'Women’s health, pregnancy, and gynecology specialty.', descriptionAr: 'تخصص صحة المرأة والحمل والنساء والولادة.', verticalSlugs: ['women-health'], relatedEntityTypeSlugs: ['clinic', 'doctor-profile'], isMentalHealth: false },
  { slug: 'reproductive-medicine', labelEn: 'Reproductive Medicine', labelAr: 'طب الإنجاب', descriptionEn: 'Reproductive medicine and fertility specialty.', descriptionAr: 'تخصص طب الإنجاب والخصوبة.', verticalSlugs: ['ivf-fertility'], relatedEntityTypeSlugs: ['ivf-center', 'fertility-clinic'], isMentalHealth: false },
  { slug: 'infertility-ivf', labelEn: 'Infertility IVF', labelAr: 'العقم وأطفال الأنابيب', descriptionEn: 'Infertility and IVF specialty.', descriptionAr: 'تخصص علاج العقم وأطفال الأنابيب.', verticalSlugs: ['ivf-fertility'], relatedEntityTypeSlugs: ['ivf-center', 'fertility-clinic'], isMentalHealth: false },
  { slug: 'dentistry', labelEn: 'Dentistry', labelAr: 'طب الأسنان', descriptionEn: 'Dental and oral healthcare specialty.', descriptionAr: 'تخصص طب الأسنان وصحة الفم.', verticalSlugs: ['dental'], relatedEntityTypeSlugs: ['dental-clinic'], isMentalHealth: false },
  { slug: 'pediatric-dentistry', labelEn: 'Pediatric Dentistry', labelAr: 'طب أسنان الأطفال', descriptionEn: 'Dental care for children.', descriptionAr: 'رعاية أسنان الأطفال.', verticalSlugs: ['dental', 'pediatrics'], relatedEntityTypeSlugs: ['dental-clinic'], isMentalHealth: false },
  { slug: 'radiology', labelEn: 'Radiology', labelAr: 'الأشعة', descriptionEn: 'Radiology and medical imaging specialty.', descriptionAr: 'تخصص الأشعة والتصوير الطبي.', verticalSlugs: ['imaging', 'diagnostics'], relatedEntityTypeSlugs: ['imaging-center'], isMentalHealth: false },
  { slug: 'pathology-laboratory', labelEn: 'Pathology Laboratory', labelAr: 'علم الأمراض والمختبرات', descriptionEn: 'Laboratory medicine and pathology specialty.', descriptionAr: 'تخصص طب المختبرات وعلم الأمراض.', verticalSlugs: ['laboratory', 'diagnostics'], relatedEntityTypeSlugs: ['laboratory-center'], isMentalHealth: false },
  { slug: 'physiotherapy', labelEn: 'Physiotherapy', labelAr: 'العلاج الطبيعي', descriptionEn: 'Physiotherapy and rehabilitation specialty.', descriptionAr: 'تخصص العلاج الطبيعي وإعادة التأهيل.', verticalSlugs: ['physiotherapy-rehabilitation'], relatedEntityTypeSlugs: ['physiotherapy-center', 'rehabilitation-center'], isMentalHealth: false },
  { slug: 'psychology', labelEn: 'Psychology', labelAr: 'علم النفس', descriptionEn: 'Psychology specialty for mental health support.', descriptionAr: 'تخصص علم النفس لدعم الصحة النفسية.', verticalSlugs: ['psychology-counseling', 'mental-health'], relatedEntityTypeSlugs: ['counseling-center'], isMentalHealth: true }
] as const satisfies readonly Specialty[];
