with region_seed (
  country_code_value,
  slug,
  name_en,
  name_ar,
  sort_order
) as (
  values
    -- Morocco regions
    ('ma'::country_code, 'tanger-tetouan-al-hoceima', 'Tanger-Tetouan-Al Hoceima', 'طنجة تطوان الحسيمة', 10),
    ('ma'::country_code, 'oriental', 'Oriental', 'الشرق', 20),
    ('ma'::country_code, 'fes-meknes', 'Fes-Meknes', 'فاس مكناس', 30),
    ('ma'::country_code, 'rabat-sale-kenitra', 'Rabat-Sale-Kenitra', 'الرباط سلا القنيطرة', 40),
    ('ma'::country_code, 'beni-mellal-khenifra', 'Beni Mellal-Khenifra', 'بني ملال خنيفرة', 50),
    ('ma'::country_code, 'casablanca-settat', 'Casablanca-Settat', 'الدار البيضاء سطات', 60),
    ('ma'::country_code, 'marrakech-safi', 'Marrakech-Safi', 'مراكش آسفي', 70),
    ('ma'::country_code, 'draa-tafilalet', 'Draa-Tafilalet', 'درعة تافيلالت', 80),
    ('ma'::country_code, 'souss-massa', 'Souss-Massa', 'سوس ماسة', 90),
    ('ma'::country_code, 'guelmim-oued-noun', 'Guelmim-Oued Noun', 'كلميم واد نون', 100),
    ('ma'::country_code, 'laayoune-sakia-el-hamra', 'Laayoune-Sakia El Hamra', 'العيون الساقية الحمراء', 110),
    ('ma'::country_code, 'dakhla-oued-ed-dahab', 'Dakhla-Oued Ed-Dahab', 'الداخلة وادي الذهب', 120),

    -- Algeria wilayas, including the post-2025 expansion to 69 wilayas
    ('dz'::country_code, 'adrar-province', 'Adrar Province', 'ولاية أدرار', 10),
    ('dz'::country_code, 'chlef-province', 'Chlef Province', 'ولاية الشلف', 20),
    ('dz'::country_code, 'laghouat-province', 'Laghouat Province', 'ولاية الأغواط', 30),
    ('dz'::country_code, 'oum-el-bouaghi-province', 'Oum El Bouaghi Province', 'ولاية أم البواقي', 40),
    ('dz'::country_code, 'batna-province', 'Batna Province', 'ولاية باتنة', 50),
    ('dz'::country_code, 'bejaia-province', 'Bejaia Province', 'ولاية بجاية', 60),
    ('dz'::country_code, 'biskra-province', 'Biskra Province', 'ولاية بسكرة', 70),
    ('dz'::country_code, 'bechar-province', 'Bechar Province', 'ولاية بشار', 80),
    ('dz'::country_code, 'blida-province', 'Blida Province', 'ولاية البليدة', 90),
    ('dz'::country_code, 'bouira-province', 'Bouira Province', 'ولاية البويرة', 100),
    ('dz'::country_code, 'tamanrasset-province', 'Tamanrasset Province', 'ولاية تمنراست', 110),
    ('dz'::country_code, 'tebessa-province', 'Tebessa Province', 'ولاية تبسة', 120),
    ('dz'::country_code, 'tlemcen-province', 'Tlemcen Province', 'ولاية تلمسان', 130),
    ('dz'::country_code, 'tiaret-province', 'Tiaret Province', 'ولاية تيارت', 140),
    ('dz'::country_code, 'tizi-ouzou-province', 'Tizi Ouzou Province', 'ولاية تيزي وزو', 150),
    ('dz'::country_code, 'algiers-province', 'Algiers Province', 'ولاية الجزائر', 160),
    ('dz'::country_code, 'djelfa-province', 'Djelfa Province', 'ولاية الجلفة', 170),
    ('dz'::country_code, 'jijel-province', 'Jijel Province', 'ولاية جيجل', 180),
    ('dz'::country_code, 'setif-province', 'Setif Province', 'ولاية سطيف', 190),
    ('dz'::country_code, 'saida-province', 'Saida Province', 'ولاية سعيدة', 200),
    ('dz'::country_code, 'skikda-province', 'Skikda Province', 'ولاية سكيكدة', 210),
    ('dz'::country_code, 'sidi-bel-abbes-province', 'Sidi Bel Abbes Province', 'ولاية سيدي بلعباس', 220),
    ('dz'::country_code, 'annaba-province', 'Annaba Province', 'ولاية عنابة', 230),
    ('dz'::country_code, 'guelma-province', 'Guelma Province', 'ولاية قالمة', 240),
    ('dz'::country_code, 'constantine-province', 'Constantine Province', 'ولاية قسنطينة', 250),
    ('dz'::country_code, 'medea-province', 'Medea Province', 'ولاية المدية', 260),
    ('dz'::country_code, 'mostaganem-province', 'Mostaganem Province', 'ولاية مستغانم', 270),
    ('dz'::country_code, 'msila-province', 'Msila Province', 'ولاية المسيلة', 280),
    ('dz'::country_code, 'mascara-province', 'Mascara Province', 'ولاية معسكر', 290),
    ('dz'::country_code, 'ouargla-province', 'Ouargla Province', 'ولاية ورقلة', 300),
    ('dz'::country_code, 'oran-province', 'Oran Province', 'ولاية وهران', 310),
    ('dz'::country_code, 'el-bayadh-province', 'El Bayadh Province', 'ولاية البيض', 320),
    ('dz'::country_code, 'illizi-province', 'Illizi Province', 'ولاية إليزي', 330),
    ('dz'::country_code, 'bordj-bou-arreridj-province', 'Bordj Bou Arreridj Province', 'ولاية برج بوعريريج', 340),
    ('dz'::country_code, 'boumerdes-province', 'Boumerdes Province', 'ولاية بومرداس', 350),
    ('dz'::country_code, 'el-tarf-province', 'El Tarf Province', 'ولاية الطارف', 360),
    ('dz'::country_code, 'tindouf-province', 'Tindouf Province', 'ولاية تندوف', 370),
    ('dz'::country_code, 'tissemsilt-province', 'Tissemsilt Province', 'ولاية تيسمسيلت', 380),
    ('dz'::country_code, 'el-oued-province', 'El Oued Province', 'ولاية الوادي', 390),
    ('dz'::country_code, 'khenchela-province', 'Khenchela Province', 'ولاية خنشلة', 400),
    ('dz'::country_code, 'souk-ahras-province', 'Souk Ahras Province', 'ولاية سوق أهراس', 410),
    ('dz'::country_code, 'tipaza-province', 'Tipaza Province', 'ولاية تيبازة', 420),
    ('dz'::country_code, 'mila-province', 'Mila Province', 'ولاية ميلة', 430),
    ('dz'::country_code, 'ain-defla-province', 'Ain Defla Province', 'ولاية عين الدفلى', 440),
    ('dz'::country_code, 'naama-province', 'Naama Province', 'ولاية النعامة', 450),
    ('dz'::country_code, 'ain-temouchent-province', 'Ain Temouchent Province', 'ولاية عين تموشنت', 460),
    ('dz'::country_code, 'ghardaia-province', 'Ghardaia Province', 'ولاية غرداية', 470),
    ('dz'::country_code, 'relizane-province', 'Relizane Province', 'ولاية غليزان', 480),
    ('dz'::country_code, 'timimoun-province', 'Timimoun Province', 'ولاية تيميمون', 490),
    ('dz'::country_code, 'bordj-badji-mokhtar-province', 'Bordj Badji Mokhtar Province', 'ولاية برج باجي مختار', 500),
    ('dz'::country_code, 'ouled-djellal-province', 'Ouled Djellal Province', 'ولاية أولاد جلال', 510),
    ('dz'::country_code, 'beni-abbes-province', 'Beni Abbes Province', 'ولاية بني عباس', 520),
    ('dz'::country_code, 'in-salah-province', 'In Salah Province', 'ولاية عين صالح', 530),
    ('dz'::country_code, 'in-guezzam-province', 'In Guezzam Province', 'ولاية عين قزام', 540),
    ('dz'::country_code, 'touggourt-province', 'Touggourt Province', 'ولاية تقرت', 550),
    ('dz'::country_code, 'djanet-province', 'Djanet Province', 'ولاية جانت', 560),
    ('dz'::country_code, 'el-mghair-province', 'El Mghair Province', 'ولاية المغير', 570),
    ('dz'::country_code, 'el-menia-province', 'El Menia Province', 'ولاية المنيعة', 580),
    ('dz'::country_code, 'aflou-province', 'Aflou Province', 'ولاية آفلو', 590),
    ('dz'::country_code, 'ain-oussera-province', 'Ain Oussera Province', 'ولاية عين وسارة', 600),
    ('dz'::country_code, 'barika-province', 'Barika Province', 'ولاية بريكة', 610),
    ('dz'::country_code, 'bir-el-ater-province', 'Bir El Ater Province', 'ولاية بئر العاتر', 620),
    ('dz'::country_code, 'bousaada-province', 'Bousaada Province', 'ولاية بوسعادة', 630),
    ('dz'::country_code, 'el-abiodh-sidi-cheikh-province', 'El Abiodh Sidi Cheikh Province', 'ولاية الأبيض سيدي الشيخ', 640),
    ('dz'::country_code, 'el-aricha-province', 'El Aricha Province', 'ولاية العريشة', 650),
    ('dz'::country_code, 'el-kantara-province', 'El Kantara Province', 'ولاية القنطرة', 660),
    ('dz'::country_code, 'ksar-chellala-province', 'Ksar Chellala Province', 'ولاية قصر الشلالة', 670),
    ('dz'::country_code, 'ksar-el-boukhari-province', 'Ksar El Boukhari Province', 'ولاية قصر البخاري', 680),
    ('dz'::country_code, 'messaad-province', 'Messaad Province', 'ولاية مسعد', 690),

    -- Tunisia governorates
    ('tn'::country_code, 'ariana-governorate', 'Ariana Governorate', 'ولاية أريانة', 10),
    ('tn'::country_code, 'beja-governorate', 'Beja Governorate', 'ولاية باجة', 20),
    ('tn'::country_code, 'ben-arous-governorate', 'Ben Arous Governorate', 'ولاية بن عروس', 30),
    ('tn'::country_code, 'bizerte-governorate', 'Bizerte Governorate', 'ولاية بنزرت', 40),
    ('tn'::country_code, 'gabes-governorate', 'Gabes Governorate', 'ولاية قابس', 50),
    ('tn'::country_code, 'gafsa-governorate', 'Gafsa Governorate', 'ولاية قفصة', 60),
    ('tn'::country_code, 'jendouba-governorate', 'Jendouba Governorate', 'ولاية جندوبة', 70),
    ('tn'::country_code, 'kairouan-governorate', 'Kairouan Governorate', 'ولاية القيروان', 80),
    ('tn'::country_code, 'kasserine-governorate', 'Kasserine Governorate', 'ولاية القصرين', 90),
    ('tn'::country_code, 'kebili-governorate', 'Kebili Governorate', 'ولاية قبلي', 100),
    ('tn'::country_code, 'kef-governorate', 'Kef Governorate', 'ولاية الكاف', 110),
    ('tn'::country_code, 'mahdia-governorate', 'Mahdia Governorate', 'ولاية المهدية', 120),
    ('tn'::country_code, 'manouba-governorate', 'Manouba Governorate', 'ولاية منوبة', 130),
    ('tn'::country_code, 'medenine-governorate', 'Medenine Governorate', 'ولاية مدنين', 140),
    ('tn'::country_code, 'monastir-governorate', 'Monastir Governorate', 'ولاية المنستير', 150),
    ('tn'::country_code, 'nabeul-governorate', 'Nabeul Governorate', 'ولاية نابل', 160),
    ('tn'::country_code, 'sfax-governorate', 'Sfax Governorate', 'ولاية صفاقس', 170),
    ('tn'::country_code, 'sidi-bouzid-governorate', 'Sidi Bouzid Governorate', 'ولاية سيدي بوزيد', 180),
    ('tn'::country_code, 'siliana-governorate', 'Siliana Governorate', 'ولاية سليانة', 190),
    ('tn'::country_code, 'sousse-governorate', 'Sousse Governorate', 'ولاية سوسة', 200),
    ('tn'::country_code, 'tataouine-governorate', 'Tataouine Governorate', 'ولاية تطاوين', 210),
    ('tn'::country_code, 'tozeur-governorate', 'Tozeur Governorate', 'ولاية توزر', 220),
    ('tn'::country_code, 'tunis-governorate', 'Tunis Governorate', 'ولاية تونس', 230),
    ('tn'::country_code, 'zaghouan-governorate', 'Zaghouan Governorate', 'ولاية زغوان', 240),

    -- Libya districts
    ('ly'::country_code, 'al-butnan-district', 'Al Butnan District', 'البطنان', 10),
    ('ly'::country_code, 'darnah-district', 'Darnah District', 'درنة', 20),
    ('ly'::country_code, 'al-jabal-al-akhdar-district', 'Al Jabal al Akhdar District', 'الجبل الأخضر', 30),
    ('ly'::country_code, 'al-marj-district', 'Al Marj District', 'المرج', 40),
    ('ly'::country_code, 'benghazi-district', 'Benghazi District', 'بنغازي', 50),
    ('ly'::country_code, 'al-wahat-district', 'Al Wahat District', 'الواحات', 60),
    ('ly'::country_code, 'al-kufrah-district', 'Al Kufrah District', 'الكفرة', 70),
    ('ly'::country_code, 'surt-district', 'Surt District', 'سرت', 80),
    ('ly'::country_code, 'misrata-district', 'Misrata District', 'مصراتة', 90),
    ('ly'::country_code, 'al-murqub-district', 'Al Murqub District', 'المرقب', 100),
    ('ly'::country_code, 'tripoli-district', 'Tripoli District', 'طرابلس', 110),
    ('ly'::country_code, 'al-jafarah-district', 'Al Jafarah District', 'الجفارة', 120),
    ('ly'::country_code, 'az-zawiyah-district', 'Az Zawiyah District', 'الزاوية', 130),
    ('ly'::country_code, 'an-nuqat-al-khams-district', 'An Nuqat al Khams District', 'النقاط الخمس', 140),
    ('ly'::country_code, 'al-jabal-al-gharbi-district', 'Al Jabal al Gharbi District', 'الجبل الغربي', 150),
    ('ly'::country_code, 'nalut-district', 'Nalut District', 'نالوت', 160),
    ('ly'::country_code, 'al-jufrah-district', 'Al Jufrah District', 'الجفرة', 170),
    ('ly'::country_code, 'wadi-ash-shati-district', 'Wadi ash Shati District', 'وادي الشاطئ', 180),
    ('ly'::country_code, 'sabha-district', 'Sabha District', 'سبها', 190),
    ('ly'::country_code, 'wadi-al-hayat-district', 'Wadi al Hayat District', 'وادي الحياة', 200),
    ('ly'::country_code, 'ghat-district', 'Ghat District', 'غات', 210),
    ('ly'::country_code, 'murzuq-district', 'Murzuq District', 'مرزق', 220),

    -- Sudan states
    ('sd'::country_code, 'khartoum-state', 'Khartoum State', 'ولاية الخرطوم', 10),
    ('sd'::country_code, 'al-jazirah-state', 'Al Jazirah State', 'ولاية الجزيرة', 20),
    ('sd'::country_code, 'white-nile-state', 'White Nile State', 'ولاية النيل الأبيض', 30),
    ('sd'::country_code, 'sennar-state', 'Sennar State', 'ولاية سنار', 40),
    ('sd'::country_code, 'blue-nile-state', 'Blue Nile State', 'ولاية النيل الأزرق', 50),
    ('sd'::country_code, 'north-kordofan-state', 'North Kordofan State', 'ولاية شمال كردفان', 60),
    ('sd'::country_code, 'west-kordofan-state', 'West Kordofan State', 'ولاية غرب كردفان', 70),
    ('sd'::country_code, 'south-kordofan-state', 'South Kordofan State', 'ولاية جنوب كردفان', 80),
    ('sd'::country_code, 'north-darfur-state', 'North Darfur State', 'ولاية شمال دارفور', 90),
    ('sd'::country_code, 'west-darfur-state', 'West Darfur State', 'ولاية غرب دارفور', 100),
    ('sd'::country_code, 'central-darfur-state', 'Central Darfur State', 'ولاية وسط دارفور', 110),
    ('sd'::country_code, 'south-darfur-state', 'South Darfur State', 'ولاية جنوب دارفور', 120),
    ('sd'::country_code, 'east-darfur-state', 'East Darfur State', 'ولاية شرق دارفور', 130),
    ('sd'::country_code, 'red-sea-state', 'Red Sea State', 'ولاية البحر الأحمر', 140),
    ('sd'::country_code, 'kassala-state', 'Kassala State', 'ولاية كسلا', 150),
    ('sd'::country_code, 'al-qadarif-state', 'Al Qadarif State', 'ولاية القضارف', 160),
    ('sd'::country_code, 'river-nile-state', 'River Nile State', 'ولاية نهر النيل', 170),
    ('sd'::country_code, 'northern-state', 'Northern State', 'الولاية الشمالية', 180),

    -- Mauritania regions
    ('mr'::country_code, 'adrar-region', 'Adrar Region', 'أدرار', 10),
    ('mr'::country_code, 'assaba-region', 'Assaba Region', 'لعصابة', 20),
    ('mr'::country_code, 'brakna-region', 'Brakna Region', 'لبراكنة', 30),
    ('mr'::country_code, 'dakhlet-nouadhibou-region', 'Dakhlet Nouadhibou Region', 'داخلة نواذيبو', 40),
    ('mr'::country_code, 'gorgol-region', 'Gorgol Region', 'كوركول', 50),
    ('mr'::country_code, 'guidimaka-region', 'Guidimaka Region', 'غيديماغا', 60),
    ('mr'::country_code, 'hodh-ech-chargui-region', 'Hodh Ech Chargui Region', 'الحوض الشرقي', 70),
    ('mr'::country_code, 'hodh-el-gharbi-region', 'Hodh El Gharbi Region', 'الحوض الغربي', 80),
    ('mr'::country_code, 'inchiri-region', 'Inchiri Region', 'إينشيري', 90),
    ('mr'::country_code, 'nouakchott-nord-region', 'Nouakchott-Nord Region', 'نواكشوط الشمالية', 100),
    ('mr'::country_code, 'nouakchott-ouest-region', 'Nouakchott-Ouest Region', 'نواكشوط الغربية', 110),
    ('mr'::country_code, 'nouakchott-sud-region', 'Nouakchott-Sud Region', 'نواكشوط الجنوبية', 120),
    ('mr'::country_code, 'tagant-region', 'Tagant Region', 'تكانت', 130),
    ('mr'::country_code, 'tiris-zemmour-region', 'Tiris Zemmour Region', 'تيرس زمور', 140),
    ('mr'::country_code, 'trarza-region', 'Trarza Region', 'الترارزه', 150)
), region_rows as (
  select
    countries.id as country_id,
    seed.slug,
    seed.name_en,
    seed.name_ar,
    seed.sort_order
  from region_seed seed
  join public.geo_countries countries
    on countries.code = seed.country_code_value
   and countries.deleted_at is null
), updated_regions as (
  update public.geo_regions target
  set
    name_en = seed.name_en,
    name_ar = seed.name_ar,
    is_active = true,
    sort_order = seed.sort_order,
    deleted_at = null,
    metadata = jsonb_build_object('seed_key', seed.slug, 'seed_phase', 'GEO-FULL-C3'),
    updated_at = now()
  from region_rows seed
  where target.country_id = seed.country_id
    and target.slug = seed.slug
  returning target.id, target.slug
)
insert into public.geo_regions (
  country_id,
  slug,
  name_en,
  name_ar,
  is_active,
  sort_order,
  metadata
)
select
  seed.country_id,
  seed.slug,
  seed.name_en,
  seed.name_ar,
  true,
  seed.sort_order,
  jsonb_build_object('seed_key', seed.slug, 'seed_phase', 'GEO-FULL-C3')
from region_rows seed
where not exists (
  select 1
  from public.geo_regions existing
  where existing.country_id = seed.country_id
    and existing.slug = seed.slug
);
