/* eslint-disable @typescript-eslint/no-explicit-any */
"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { createSupabaseServiceRoleClient } from "@/lib/supabase/service-role";
import type { Json } from "@/lib/supabase/types";
import { writeAdminAuditEvent } from "@/server/admin/audit-log";
import { isCmsContentType, isValidUuid, type CmsStatus } from "@/server/admin/cms-content";
import { requireAdminPermission } from "@/server/admin/permissions";

type ActionState = { ok: boolean; message: string };
const max = { contentKey: 160, slug: 160, title: 220, summary: 500, seoTitle: 70, seoDescription: 170, reviewNote: 1000 };
const entryTransitions: Record<CmsStatus, CmsStatus[]> = { draft: ["in_review", "archived"], in_review: ["approved", "rejected"], approved: ["archived"], rejected: [], published: [], archived: ["draft"] };
const revisionTransitions: Record<CmsStatus, CmsStatus[]> = { draft: ["in_review"], in_review: ["approved", "rejected"], approved: ["archived"], rejected: [], published: [], archived: [] };

function text(formData: FormData, key: string, limit: number, required = false): string | null { const raw = String(formData.get(key) ?? "").trim(); if (!raw) { if (required) throw new Error(`${key} is required.`); return null; } if (raw.length > limit) throw new Error(`${key} is too long.`); return raw; }
function parseJson(formData: FormData, key: string): Json { const raw = String(formData.get(key) ?? "").trim(); if (!raw) return {}; const parsed = JSON.parse(raw); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error(`${key} must be a JSON object.`); return parsed as Json; }
function locale(formData: FormData): "en" | "ar" | null { const value = String(formData.get("locale") ?? "").trim(); if (!value) return null; if (value === "en" || value === "ar") return value; throw new Error("Locale must be English, Arabic, or blank."); }
function safeError(error: unknown): ActionState { return { ok: false, message: error instanceof SyntaxError ? "JSON fields must contain valid JSON objects." : error instanceof Error ? error.message : "CMS action could not be completed." }; }
function revisionPayload(formData: FormData) { return { title_en: text(formData, "titleEn", max.title), title_ar: text(formData, "titleAr", max.title), summary_en: text(formData, "summaryEn", max.summary), summary_ar: text(formData, "summaryAr", max.summary), seo_title_en: text(formData, "seoTitleEn", max.seoTitle), seo_title_ar: text(formData, "seoTitleAr", max.seoTitle), seo_description_en: text(formData, "seoDescriptionEn", max.seoDescription), seo_description_ar: text(formData, "seoDescriptionAr", max.seoDescription), body_en: parseJson(formData, "bodyEn"), body_ar: parseJson(formData, "bodyAr"), metadata: parseJson(formData, "metadata"), review_note: text(formData, "reviewNote", max.reviewNote) }; }
async function latestRevisionNumber(supabase: any, entryId: string): Promise<number> { const { data } = await supabase.from("cms_content_revisions").select("revision_number").eq("entry_id", entryId).order("revision_number", { ascending: false }).limit(1).maybeSingle(); return data?.revision_number ?? 0; }
async function getEntry(supabase: any, entryId: string) { const { data, error } = await supabase.from("cms_content_entries").select("*").eq("id", entryId).maybeSingle(); if (error || !data) throw new Error("CMS entry could not be loaded."); return data as Record<string, any>; }
async function getRevision(supabase: any, revisionId: string) { const { data, error } = await supabase.from("cms_content_revisions").select("*").eq("id", revisionId).maybeSingle(); if (error || !data) throw new Error("CMS revision could not be loaded."); return data as Record<string, any>; }

export async function createAdminCmsContentEntry(_prev: ActionState, formData: FormData): Promise<ActionState> { let newId: string | null = null; try { const admin = await requireAdminPermission("content.create"); const contentKey = text(formData, "contentKey", max.contentKey, true)!; const contentType = String(formData.get("contentType") ?? ""); if (!isCmsContentType(contentType)) throw new Error("Content type is not allowed."); const supabase = createSupabaseServiceRoleClient() as any; const entryPayload = { created_by_profile_id: admin.profile.id, updated_by_profile_id: admin.profile.id, content_key: contentKey, content_type: contentType, locale: locale(formData), country: "om", title_en: text(formData, "titleEn", max.title), title_ar: text(formData, "titleAr", max.title), slug: text(formData, "slug", max.slug), metadata: parseJson(formData, "metadata"), status: "draft" };
    const { data: entry, error } = await supabase.from("cms_content_entries").insert(entryPayload).select("*").single(); if (error) throw new Error("CMS entry could not be created."); const rev = revisionPayload(formData); const { data: revision, error: revError } = await supabase.from("cms_content_revisions").insert({ ...rev, entry_id: entry.id, created_by_profile_id: admin.profile.id, revision_number: 1, status: "draft" }).select("*").single(); if (revError) throw new Error("CMS revision could not be created."); await supabase.from("cms_content_entries").update({ current_revision_id: revision.id }).eq("id", entry.id); newId = entry.id; await writeAdminAuditEvent({ admin, permissionKey: "content.create", action: "cms_content.entry_created", entityType: "cms_content_entry", entityId: entry.id, targetTable: "cms_content_entries", summary: "CMS content entry created as an internal draft.", newValues: { status: "draft", title: entry.title_en ?? entry.title_ar, content_type: contentType, locale: entry.locale, content_key: contentKey } }); await writeAdminAuditEvent({ admin, permissionKey: "content.create", action: "cms_content.revision_created", entityType: "cms_content_revision", entityId: revision.id, targetTable: "cms_content_revisions", summary: "Initial CMS content revision created.", newValues: { status: "draft", title: revision.title_en ?? revision.title_ar, revision_number: 1 } }); } catch (error) { return safeError(error); } revalidatePath("/admin/content"); redirect(`/admin/content/${newId}`); }

export async function updateAdminCmsContentDraft(_prev: ActionState, formData: FormData): Promise<ActionState> { try { const admin = await requireAdminPermission("content.update"); const entryId = String(formData.get("entryId") ?? ""); if (!isValidUuid(entryId)) throw new Error("Invalid CMS entry."); const supabase = createSupabaseServiceRoleClient() as any; const entry = await getEntry(supabase, entryId); if (!["draft", "rejected"].includes(entry.status)) throw new Error("Only draft or rejected CMS entries can be edited."); const payload = revisionPayload(formData); const entryPatch = { updated_by_profile_id: admin.profile.id, title_en: payload.title_en, title_ar: payload.title_ar, slug: text(formData, "slug", max.slug), metadata: payload.metadata, status: "draft", is_archived: false };
    const { error } = await supabase.from("cms_content_entries").update(entryPatch).eq("id", entryId); if (error) throw new Error("CMS entry could not be updated."); const currentRevisionId = entry.current_revision_id; if (currentRevisionId) { await supabase.from("cms_content_revisions").update({ ...payload, status: "draft" }).eq("id", currentRevisionId); await writeAdminAuditEvent({ admin, permissionKey: "content.update", action: "cms_content.revision_updated", entityType: "cms_content_revision", entityId: currentRevisionId, targetTable: "cms_content_revisions", summary: "CMS draft revision updated.", newValues: { status: "draft", title: payload.title_en ?? payload.title_ar } }); } await writeAdminAuditEvent({ admin, permissionKey: "content.update", action: "cms_content.entry_updated", entityType: "cms_content_entry", entityId: entryId, targetTable: "cms_content_entries", summary: "CMS content entry draft metadata updated.", oldValues: { status: entry.status, title: entry.title_en ?? entry.title_ar }, newValues: { status: "draft", title: payload.title_en ?? payload.title_ar, content_key: entry.content_key, content_type: entry.content_type, locale: entry.locale } }); revalidatePath(`/admin/content/${entryId}`); return { ok: true, message: "CMS draft saved." }; } catch (error) { return safeError(error); } }

export async function createAdminCmsContentRevision(entryId: string): Promise<void> { const admin = await requireAdminPermission("content.update"); if (!isValidUuid(entryId)) redirect("/admin/content"); const supabase = createSupabaseServiceRoleClient() as any; const entry = await getEntry(supabase, entryId); const source = entry.current_revision_id ? await getRevision(supabase, entry.current_revision_id) : {}; const number = (await latestRevisionNumber(supabase, entryId)) + 1; const { data: revision } = await supabase.from("cms_content_revisions").insert({ entry_id: entryId, created_by_profile_id: admin.profile.id, revision_number: number, status: "draft", title_en: source.title_en ?? entry.title_en, title_ar: source.title_ar ?? entry.title_ar, summary_en: source.summary_en ?? null, summary_ar: source.summary_ar ?? null, body_en: source.body_en ?? {}, body_ar: source.body_ar ?? {}, seo_title_en: source.seo_title_en ?? null, seo_title_ar: source.seo_title_ar ?? null, seo_description_en: source.seo_description_en ?? null, seo_description_ar: source.seo_description_ar ?? null, metadata: source.metadata ?? {} }).select("*").single(); if (revision) { await supabase.from("cms_content_entries").update({ current_revision_id: revision.id, status: "draft", is_archived: false }).eq("id", entryId); await writeAdminAuditEvent({ admin, permissionKey: "content.update", action: "cms_content.revision_created", entityType: "cms_content_revision", entityId: revision.id, targetTable: "cms_content_revisions", summary: "New CMS draft revision created.", newValues: { status: "draft", revision_number: number, title: revision.title_en ?? revision.title_ar } }); } revalidatePath(`/admin/content/${entryId}`); }

async function transitionRevision(revisionId: string, next: CmsStatus, permissionKey: any, action: any, note?: string) { const admin = await requireAdminPermission(permissionKey); if (!isValidUuid(revisionId)) throw new Error("Invalid CMS revision."); const supabase = createSupabaseServiceRoleClient() as any; const revision = await getRevision(supabase, revisionId); if (!revisionTransitions[revision.status as CmsStatus]?.includes(next)) throw new Error("CMS revision status transition is not allowed."); const patch: Record<string, any> = { status: next, review_note: note ?? revision.review_note }; if (next === "approved") { patch.approved_at = new Date().toISOString(); patch.approved_by_profile_id = admin.profile.id; } if (next === "rejected") { patch.rejected_at = new Date().toISOString(); patch.rejected_by_profile_id = admin.profile.id; } await supabase.from("cms_content_revisions").update(patch).eq("id", revisionId); await supabase.from("cms_content_entries").update({ status: next, updated_by_profile_id: admin.profile.id }).eq("id", revision.entry_id); await writeAdminAuditEvent({ admin, permissionKey, action, entityType: "cms_content_revision", entityId: revisionId, targetTable: "cms_content_revisions", summary: `CMS revision moved to ${next}.`, oldValues: { status: revision.status, revision_number: revision.revision_number, title: revision.title_en ?? revision.title_ar }, newValues: { status: next, revision_number: revision.revision_number, title: revision.title_en ?? revision.title_ar } }); revalidatePath(`/admin/content/${revision.entry_id}`); }
export async function submitAdminCmsRevisionForReview(formData: FormData) { await transitionRevision(String(formData.get("revisionId") ?? ""), "in_review", "content.submit_review", "cms_content.submitted_for_review", text(formData, "reviewNote", max.reviewNote) ?? undefined); }
export async function approveAdminCmsRevision(formData: FormData) { await transitionRevision(String(formData.get("revisionId") ?? ""), "approved", "content.approve", "cms_content.revision_approved", text(formData, "reviewNote", max.reviewNote) ?? undefined); }
export async function rejectAdminCmsRevision(formData: FormData) { await transitionRevision(String(formData.get("revisionId") ?? ""), "rejected", "content.reject", "cms_content.revision_rejected", text(formData, "reviewNote", max.reviewNote) ?? undefined); }

export async function archiveAdminCmsContentEntry(formData: FormData) { const admin = await requireAdminPermission("content.archive"); const entryId = String(formData.get("entryId") ?? ""); if (!isValidUuid(entryId)) return; const supabase = createSupabaseServiceRoleClient() as any; const entry = await getEntry(supabase, entryId); if (!entryTransitions[entry.status as CmsStatus]?.includes("archived")) return; await supabase.from("cms_content_entries").update({ status: "archived", is_archived: true, updated_by_profile_id: admin.profile.id }).eq("id", entryId); await writeAdminAuditEvent({ admin, permissionKey: "content.archive", action: "cms_content.entry_archived", entityType: "cms_content_entry", entityId: entryId, targetTable: "cms_content_entries", summary: "CMS content entry archived internally.", oldValues: { status: entry.status, content_key: entry.content_key }, newValues: { status: "archived", content_key: entry.content_key } }); revalidatePath(`/admin/content/${entryId}`); }
export async function restoreAdminCmsContentEntry(formData: FormData) { const admin = await requireAdminPermission("content.archive"); const entryId = String(formData.get("entryId") ?? ""); if (!isValidUuid(entryId)) return; const supabase = createSupabaseServiceRoleClient() as any; const entry = await getEntry(supabase, entryId); if (!entryTransitions[entry.status as CmsStatus]?.includes("draft")) return; await supabase.from("cms_content_entries").update({ status: "draft", is_archived: false, updated_by_profile_id: admin.profile.id }).eq("id", entryId); await writeAdminAuditEvent({ admin, permissionKey: "content.archive", action: "cms_content.entry_restored", entityType: "cms_content_entry", entityId: entryId, targetTable: "cms_content_entries", summary: "CMS content entry restored to draft internally.", oldValues: { status: entry.status, content_key: entry.content_key }, newValues: { status: "draft", content_key: entry.content_key } }); revalidatePath(`/admin/content/${entryId}`); }
