'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

import { drMuscatSupportWhatsAppUrl } from '@/components/public-2026/home/support-contact-2026';
import { countryOptions2026, getAreaOptionsForCity2026, omanCityOptions2026 } from '@/components/public-2026/location/location-options-2026';
import type { SupportedCountry, SupportedLocale } from '@/lib/i18n/config';
import { publicArticlesRoute, publicDiscoveryRoute, publicProviderRoute } from '@/lib/routes/public';

type DiscoveryKind = 'doctors' | 'centers' | 'pharmacies' | 'labs' | 'services' | 'search';
type Props = { locale: SupportedLocale; country: SupportedCountry; kind: DiscoveryKind; liveContent?: React.ReactNode };
type Sample = { name: string; category: string; location: string; hours: string; description: string; tags: readonly string[] };
type Copy = {
  title: string; subtitle: string; eyebrow: string; searchPlaceholder: string; filtersTitle: string; category: string; language: string; providerType: string; specialty: string; sort: string; sorts: readonly string[]; resultsTitle: string; resultsNote: string; preview: string; noReviews: string; view: string; whatsapp: string; call: string; directions: string; actionNotice: string; mapTitle: string; mapBody: string; relatedTitle: string; related: readonly string[]; faqTitle: string; faqs: readonly { q: string; a: string }[]; safetyTitle: string; safety: string; country: string; city: string; area: string; allAreas: string; allCategories: string; samples: readonly Sample[];
};

const shared = {
  en: { eyebrow: 'Healthcare discovery in Oman', preview: 'Reviewed sample preview', noReviews: 'No reviews yet', view: 'View profile', whatsapp: 'WhatsApp', call: 'Call', directions: 'Directions', actionNotice: 'This preview action will connect after an approved provider profile is available.', mapTitle: 'Map preview', mapBody: 'Use city and area filters to prepare a local discovery view. Live map results will use approved provider data.', safetyTitle: 'Discovery and safety note', safety: 'DrMuscat is a healthcare discovery platform. Confirm availability, credentials, services, preparation instructions, and contact details directly with the provider. This page does not provide diagnosis, emergency care, or medical advice.', country: 'Country', city: 'City', area: 'Area', allAreas: 'All areas', allCategories: 'All categories', filtersTitle: 'Refine your discovery', sort: 'Sort', sorts: ['Recommended', 'Near me', 'Recently updated', 'A–Z'] },
  ar: { eyebrow: 'اكتشاف الرعاية الصحية في عُمان', preview: 'معاينة نموذجية للمراجعة', noReviews: 'لا توجد مراجعات بعد', view: 'عرض الملف', whatsapp: 'واتساب', call: 'اتصال', directions: 'الاتجاهات', actionNotice: 'سيتم ربط هذا الإجراء بعد توفر ملف مقدم رعاية معتمد.', mapTitle: 'معاينة الخريطة', mapBody: 'استخدم مرشحات المدينة والمنطقة لتجهيز عرض اكتشاف محلي. ستعتمد نتائج الخريطة المباشرة على بيانات مقدمي الرعاية المعتمدة.', safetyTitle: 'ملاحظة الاكتشاف والسلامة', safety: 'دكتور مسقط منصة لاكتشاف الرعاية الصحية. يرجى تأكيد التوفر والاعتمادات والخدمات وتعليمات التحضير وبيانات التواصل مباشرة مع مقدم الرعاية. لا تقدم هذه الصفحة تشخيصاً أو رعاية طارئة أو نصيحة طبية.', country: 'الدولة', city: 'المدينة', area: 'المنطقة', allAreas: 'كل المناطق', allCategories: 'كل الفئات', filtersTitle: 'خصص بحثك', sort: 'الترتيب', sorts: ['موصى به', 'بالقرب مني', 'محدث مؤخراً', 'أ–ي'] },
} as const;

const copyByKind: Record<DiscoveryKind, Record<SupportedLocale, Omit<Copy, keyof typeof shared.en>>> = {
  doctors: {
    en: { title: 'Find doctors in Oman', subtitle: 'Browse doctor profiles by specialty, city, area, and care need. DrMuscat helps you discover providers without fake rankings or medical claims.', searchPlaceholder: 'Search doctor name, specialty, or care need', category: 'Specialty', language: 'Language', providerType: 'Doctor type', specialty: 'Specialty', resultsTitle: 'Doctor profile previews', resultsNote: 'Sample discovery cards show how approved doctor profiles can be presented.', relatedTitle: 'Explore doctor discovery', related: ['Doctors by specialty', 'Doctors by area', 'Clinics and medical centers', 'Health guides'], faqTitle: 'Doctor discovery FAQ', faqs: [{ q: 'How do I find a doctor near me?', a: 'Use the city and area filters, then confirm the clinic location directly.' }, { q: 'Are doctors ranked by medical quality?', a: 'No. DrMuscat does not present paid visibility or previews as medical quality ranking.' }, { q: 'Can I contact a clinic directly?', a: 'Approved profiles can provide direct contact actions.' }, { q: 'Are reviews moderated?', a: 'Any future public reviews should be moderated before display.' }], samples: [{ name: 'Doctor profile preview', category: 'General practice', location: 'Muscat · Al Khuwair', hours: 'Hours available after profile approval', description: 'A sample doctor discovery profile with specialty, clinic affiliation, languages, and practical contact details.', tags: ['English', 'Arabic', 'Clinic affiliation'] }, { name: 'Specialist profile preview', category: 'Pediatrics', location: 'Muscat · Qurum', hours: 'Confirm hours directly', description: 'A preview of a specialty-focused profile without ratings, rankings, or availability claims.', tags: ['Specialty interests', 'Training preview', 'No reviews yet'] }] },
    ar: { title: 'ابحث عن أطباء في عُمان', subtitle: 'تصفح ملفات الأطباء حسب التخصص والمدينة والمنطقة واحتياجك الصحي، دون تقييمات مزيفة أو ادعاءات طبية.', searchPlaceholder: 'ابحث باسم الطبيب أو التخصص أو الاحتياج الصحي', category: 'التخصص', language: 'اللغة', providerType: 'نوع الطبيب', specialty: 'التخصص', resultsTitle: 'معاينات ملفات الأطباء', resultsNote: 'توضح بطاقات الاكتشاف النموذجية طريقة عرض ملفات الأطباء المعتمدة.', relatedTitle: 'استكشف اكتشاف الأطباء', related: ['الأطباء حسب التخصص', 'الأطباء حسب المنطقة', 'العيادات والمراكز الطبية', 'الأدلة الصحية'], faqTitle: 'أسئلة اكتشاف الأطباء', faqs: [{ q: 'كيف أجد طبيباً بالقرب مني؟', a: 'استخدم مرشحات المدينة والمنطقة ثم أكد موقع العيادة مباشرة.' }, { q: 'هل يتم ترتيب الأطباء حسب الجودة الطبية؟', a: 'لا. لا تعرض دكتور مسقط الظهور المدفوع أو المعاينات كتصنيف للجودة الطبية.' }, { q: 'هل يمكنني التواصل مع العيادة مباشرة؟', a: 'يمكن للملفات المعتمدة توفير إجراءات تواصل مباشرة.' }, { q: 'هل تتم مراجعة التعليقات؟', a: 'ينبغي مراجعة أي تعليقات عامة مستقبلية قبل عرضها.' }], samples: [{ name: 'معاينة ملف طبيب', category: 'الطب العام', location: 'مسقط · الخوير', hours: 'تتوفر الساعات بعد اعتماد الملف', description: 'ملف اكتشاف نموذجي يعرض التخصص والعيادة واللغات وبيانات التواصل العملية.', tags: ['الإنجليزية', 'العربية', 'العيادة الحالية'] }, { name: 'معاينة ملف اختصاصي', category: 'طب الأطفال', location: 'مسقط · القرم', hours: 'أكد الساعات مباشرة', description: 'معاينة لملف يركز على التخصص دون تقييمات أو تصنيفات أو ادعاءات توفر.', tags: ['اهتمامات التخصص', 'معاينة التدريب', 'لا توجد مراجعات بعد'] }] },
  },
  centers: {
    en: { title: 'Find clinics and medical centers in Oman', subtitle: 'Discover clinics and centers by category, service, city, and area, then confirm details directly with the provider.', searchPlaceholder: 'Search center name, service, or category', category: 'Center category', language: 'Language', providerType: 'Provider type', specialty: 'Service', resultsTitle: 'Center profile previews', resultsNote: 'Sample cards illustrate approved center profiles without fake rankings or claims.', relatedTitle: 'Browse center discovery', related: ['Dental clinics', 'General clinics', 'Centers by area', 'Provider articles'], faqTitle: 'Center discovery FAQ', faqs: [{ q: 'How do I find a clinic by area?', a: 'Choose a city and area to narrow your discovery.' }, { q: 'Can centers claim their profile?', a: 'Providers can request a listing review through DrMuscat.' }, { q: 'Does DrMuscat verify every detail?', a: 'Users should always confirm current details directly with the center.' }, { q: 'How do I report incorrect information?', a: 'Contact DrMuscat support with the profile and correction details.' }], samples: [{ name: 'Medical center profile preview', category: 'Multi-service clinic', location: 'Muscat · Al Ghubrah', hours: 'Hours preview after approval', description: 'A sample center profile for services, location, practical information, and direct contact actions.', tags: ['General clinics', 'Diagnostics', 'Map section'] }, { name: 'Clinic profile preview', category: 'Dental clinic', location: 'Seeb · Al Hail', hours: 'Confirm hours directly', description: 'A calm preview of a clinic profile with honest discovery information and no quality ranking.', tags: ['Dental care', 'Contact actions', 'Claim profile'] }] },
    ar: { title: 'ابحث عن عيادات ومراكز طبية في عُمان', subtitle: 'اكتشف العيادات والمراكز حسب الفئة والخدمة والمدينة والمنطقة، ثم أكد التفاصيل مباشرة مع مقدم الرعاية.', searchPlaceholder: 'ابحث باسم المركز أو الخدمة أو الفئة', category: 'فئة المركز', language: 'اللغة', providerType: 'نوع مقدم الرعاية', specialty: 'الخدمة', resultsTitle: 'معاينات ملفات المراكز', resultsNote: 'توضح البطاقات النموذجية ملفات المراكز المعتمدة دون تصنيفات أو ادعاءات مزيفة.', relatedTitle: 'تصفح اكتشاف المراكز', related: ['عيادات الأسنان', 'العيادات العامة', 'المراكز حسب المنطقة', 'مقالات مقدمي الرعاية'], faqTitle: 'أسئلة اكتشاف المراكز', faqs: [{ q: 'كيف أجد عيادة حسب المنطقة؟', a: 'اختر المدينة والمنطقة لتضييق نطاق الاكتشاف.' }, { q: 'هل يمكن للمراكز المطالبة بملفها؟', a: 'يمكن لمقدمي الرعاية طلب مراجعة الإدراج عبر دكتور مسقط.' }, { q: 'هل يتحقق دكتور مسقط من كل التفاصيل؟', a: 'يجب دائماً تأكيد التفاصيل الحالية مباشرة مع المركز.' }, { q: 'كيف أبلغ عن معلومات غير صحيحة؟', a: 'تواصل مع دعم دكتور مسقط وأرسل الملف وتفاصيل التصحيح.' }], samples: [{ name: 'معاينة ملف مركز طبي', category: 'عيادة متعددة الخدمات', location: 'مسقط · الغبرة', hours: 'معاينة الساعات بعد الاعتماد', description: 'ملف مركز نموذجي يعرض الخدمات والموقع والمعلومات العملية وإجراءات التواصل المباشر.', tags: ['عيادات عامة', 'تشخيص', 'قسم الخريطة'] }, { name: 'معاينة ملف عيادة', category: 'عيادة أسنان', location: 'السيب · الحيل', hours: 'أكد الساعات مباشرة', description: 'معاينة هادئة لملف عيادة بمعلومات اكتشاف صادقة ودون تصنيف للجودة.', tags: ['رعاية الأسنان', 'إجراءات التواصل', 'المطالبة بالملف'] }] },
  },
  pharmacies: {
    en: { title: 'Find pharmacies in Oman', subtitle: 'Browse pharmacy discovery previews by city and area, and always confirm medicine availability and services directly.', searchPlaceholder: 'Search pharmacy name or service', category: 'Pharmacy service', language: 'Language', providerType: 'Pharmacy type', specialty: 'Service', resultsTitle: 'Pharmacy profile previews', resultsNote: 'Medicine availability is never implied by these sample cards.', relatedTitle: 'Pharmacy discovery in Oman', related: ['Pharmacies by area', 'Prescription services', 'Delivery information', 'Pharmacy guides'], faqTitle: 'Pharmacy discovery FAQ', faqs: [{ q: 'Can I find pharmacies by area?', a: 'Yes. Use city and area filters to prepare a local search.' }, { q: 'Should I confirm medicine availability?', a: 'Yes. Always contact the pharmacy directly.' }, { q: 'Is delivery shown?', a: 'Approved profiles may describe delivery services where confirmed.' }, { q: 'Can pharmacies list services?', a: 'Providers can request a reviewed public listing.' }], samples: [{ name: 'Pharmacy profile preview', category: 'Community pharmacy', location: 'Muscat · Azaiba', hours: 'Confirm opening hours directly', description: 'A sample pharmacy profile for contact details, location, and confirmed service information.', tags: ['Prescription service', 'General pharmacy services', 'Availability must be confirmed'] }, { name: 'Pharmacy service preview', category: 'Pharmacy', location: 'Sohar · Central area', hours: 'Hours available after approval', description: 'A preview card that does not claim medicine stock, delivery, or 24-hour availability.', tags: ['Service preview', 'Directions', 'No stock claims'] }] },
    ar: { title: 'ابحث عن صيدليات في عُمان', subtitle: 'تصفح معاينات اكتشاف الصيدليات حسب المدينة والمنطقة، وأكد دائماً توفر الأدوية والخدمات مباشرة.', searchPlaceholder: 'ابحث باسم الصيدلية أو الخدمة', category: 'خدمة الصيدلية', language: 'اللغة', providerType: 'نوع الصيدلية', specialty: 'الخدمة', resultsTitle: 'معاينات ملفات الصيدليات', resultsNote: 'لا تشير هذه البطاقات النموذجية إلى توفر أي دواء.', relatedTitle: 'اكتشاف الصيدليات في عُمان', related: ['الصيدليات حسب المنطقة', 'خدمات الوصفات', 'معلومات التوصيل', 'أدلة الصيدليات'], faqTitle: 'أسئلة اكتشاف الصيدليات', faqs: [{ q: 'هل يمكنني العثور على صيدليات حسب المنطقة؟', a: 'نعم. استخدم مرشحات المدينة والمنطقة لتجهيز بحث محلي.' }, { q: 'هل يجب تأكيد توفر الدواء؟', a: 'نعم. تواصل دائماً مع الصيدلية مباشرة.' }, { q: 'هل يتم عرض التوصيل؟', a: 'قد تصف الملفات المعتمدة خدمات التوصيل عند تأكيدها.' }, { q: 'هل يمكن للصيدليات إدراج خدماتها؟', a: 'يمكن لمقدمي الرعاية طلب إدراج عام خاضع للمراجعة.' }], samples: [{ name: 'معاينة ملف صيدلية', category: 'صيدلية مجتمعية', location: 'مسقط · العذيبة', hours: 'أكد ساعات العمل مباشرة', description: 'ملف صيدلية نموذجي يعرض بيانات التواصل والموقع ومعلومات الخدمات المؤكدة.', tags: ['خدمة الوصفات', 'خدمات صيدلية عامة', 'يجب تأكيد التوفر'] }, { name: 'معاينة خدمة صيدلية', category: 'صيدلية', location: 'صحار · المنطقة المركزية', hours: 'تتوفر الساعات بعد الاعتماد', description: 'بطاقة معاينة لا تدعي توفر المخزون أو التوصيل أو العمل على مدار الساعة.', tags: ['معاينة الخدمة', 'الاتجاهات', 'لا ادعاءات مخزون'] }] },
  },
  labs: {
    en: { title: 'Find medical laboratories in Oman', subtitle: 'Discover laboratory profiles by city, area, and test category, then confirm preparation instructions and pricing directly.', searchPlaceholder: 'Search laboratory or test category', category: 'Test category', language: 'Language', providerType: 'Laboratory type', specialty: 'Test category', resultsTitle: 'Laboratory profile previews', resultsNote: 'Always confirm test availability, preparation instructions, and pricing directly with the lab.', relatedTitle: 'Laboratory discovery', related: ['Labs by area', 'Routine diagnostics', 'Blood test guides', 'Home collection information'], faqTitle: 'Laboratory discovery FAQ', faqs: [{ q: 'Can I search labs by test type?', a: 'Use the test-category filter as a discovery starting point.' }, { q: 'Should I confirm preparation requirements?', a: 'Yes. Preparation instructions must come directly from the lab or your clinician.' }, { q: 'Is home sample collection available?', a: 'Only rely on this service when an approved profile confirms it.' }, { q: 'Are prices shown?', a: 'Confirm current pricing directly with the laboratory.' }], samples: [{ name: 'Laboratory profile preview', category: 'Medical laboratory', location: 'Muscat · Qurum', hours: 'Confirm collection hours directly', description: 'A sample laboratory profile for test categories, location, and practical contact details.', tags: ['Blood tests', 'Routine diagnostics', 'Preparation must be confirmed'] }, { name: 'Diagnostic lab preview', category: 'Diagnostics', location: 'Salalah · Central area', hours: 'Hours available after approval', description: 'A preview that avoids claims about test availability, turnaround time, or pricing.', tags: ['Testing preview', 'Home collection if confirmed', 'Contact lab directly'] }] },
    ar: { title: 'ابحث عن مختبرات طبية في عُمان', subtitle: 'اكتشف ملفات المختبرات حسب المدينة والمنطقة وفئة الفحص، ثم أكد تعليمات التحضير والأسعار مباشرة.', searchPlaceholder: 'ابحث عن مختبر أو فئة فحص', category: 'فئة الفحص', language: 'اللغة', providerType: 'نوع المختبر', specialty: 'فئة الفحص', resultsTitle: 'معاينات ملفات المختبرات', resultsNote: 'أكد دائماً توفر الفحص وتعليمات التحضير والأسعار مباشرة مع المختبر.', relatedTitle: 'اكتشاف المختبرات', related: ['المختبرات حسب المنطقة', 'التشخيص الروتيني', 'أدلة فحوصات الدم', 'معلومات السحب المنزلي'], faqTitle: 'أسئلة اكتشاف المختبرات', faqs: [{ q: 'هل يمكنني البحث عن المختبرات حسب نوع الفحص؟', a: 'استخدم مرشح فئة الفحص كنقطة بداية للاكتشاف.' }, { q: 'هل يجب تأكيد متطلبات التحضير؟', a: 'نعم. يجب أن تأتي تعليمات التحضير مباشرة من المختبر أو الطبيب.' }, { q: 'هل يتوفر سحب العينات من المنزل؟', a: 'اعتمد على هذه الخدمة فقط عندما يؤكدها ملف معتمد.' }, { q: 'هل تظهر الأسعار؟', a: 'أكد الأسعار الحالية مباشرة مع المختبر.' }], samples: [{ name: 'معاينة ملف مختبر', category: 'مختبر طبي', location: 'مسقط · القرم', hours: 'أكد ساعات جمع العينات مباشرة', description: 'ملف مختبر نموذجي يعرض فئات الفحوصات والموقع وبيانات التواصل العملية.', tags: ['فحوصات الدم', 'تشخيص روتيني', 'يجب تأكيد التحضير'] }, { name: 'معاينة مختبر تشخيصي', category: 'تشخيص', location: 'صلالة · المنطقة المركزية', hours: 'تتوفر الساعات بعد الاعتماد', description: 'معاينة تتجنب ادعاءات توفر الفحص أو وقت النتيجة أو السعر.', tags: ['معاينة الفحوصات', 'سحب منزلي عند التأكيد', 'تواصل مباشرة'] }] },
  },
  services: {
    en: { title: 'Explore healthcare services in Oman', subtitle: 'Browse healthcare, dental, wellness, diagnostics, pharmacy, and veterinary discovery categories across Oman.', searchPlaceholder: 'Search a healthcare service', category: 'Service category', language: 'Language', providerType: 'Provider type', specialty: 'Service', resultsTitle: 'Explore service categories', resultsNote: 'Use these categories to open a relevant discovery search. They are not medical recommendations.', relatedTitle: 'Popular service discovery', related: ['Dental', 'Dermatology', 'Pediatrics', 'Eye clinics', 'Women’s health', 'Physiotherapy', 'Nutrition', 'Beauty clinics', 'Wellness', 'Laboratories', 'Pharmacies', 'Veterinary care', 'General clinics', 'Diagnostics'], faqTitle: 'Healthcare services FAQ', faqs: [{ q: 'How do service categories work?', a: 'Categories help organize discovery; they do not diagnose a care need.' }, { q: 'Can I search by area?', a: 'Yes. Select a city and dependent area.' }, { q: 'Are emergency services listed?', a: 'DrMuscat is not an emergency service. Use official emergency channels when needed.' }, { q: 'Can providers request listing?', a: 'Providers can request onboarding for review.' }], samples: [{ name: 'Dental services', category: 'Service category', location: 'Available across Oman', hours: 'Provider hours vary', description: 'Discover dental clinic profiles and confirm services directly.', tags: ['Clinics', 'Area filters', 'Provider profiles'] }, { name: 'Physiotherapy services', category: 'Service category', location: 'Available across Oman', hours: 'Provider hours vary', description: 'Explore physiotherapy provider profiles without medical ranking claims.', tags: ['Wellness', 'Contact providers', 'Discovery only'] }] },
    ar: { title: 'استكشف خدمات الرعاية الصحية في عُمان', subtitle: 'تصفح فئات اكتشاف الرعاية الصحية والأسنان والعافية والتشخيص والصيدليات والبيطرة في عُمان.', searchPlaceholder: 'ابحث عن خدمة رعاية صحية', category: 'فئة الخدمة', language: 'اللغة', providerType: 'نوع مقدم الرعاية', specialty: 'الخدمة', resultsTitle: 'استكشف فئات الخدمات', resultsNote: 'استخدم هذه الفئات لفتح بحث اكتشاف مناسب، وهي ليست توصيات طبية.', relatedTitle: 'اكتشاف الخدمات الشائعة', related: ['الأسنان', 'الجلدية', 'طب الأطفال', 'عيادات العيون', 'صحة المرأة', 'العلاج الطبيعي', 'التغذية', 'عيادات التجميل', 'العافية', 'المختبرات', 'الصيدليات', 'الرعاية البيطرية', 'العيادات العامة', 'التشخيص'], faqTitle: 'أسئلة خدمات الرعاية الصحية', faqs: [{ q: 'كيف تعمل فئات الخدمات؟', a: 'تساعد الفئات على تنظيم الاكتشاف ولا تشخص الاحتياج الصحي.' }, { q: 'هل يمكنني البحث حسب المنطقة؟', a: 'نعم. اختر المدينة ثم المنطقة التابعة لها.' }, { q: 'هل يتم إدراج خدمات الطوارئ؟', a: 'دكتور مسقط ليست خدمة طوارئ. استخدم القنوات الرسمية عند الحاجة.' }, { q: 'هل يمكن لمقدمي الرعاية طلب الإدراج؟', a: 'يمكن لمقدمي الرعاية طلب الانضمام للمراجعة.' }], samples: [{ name: 'خدمات الأسنان', category: 'فئة خدمة', location: 'متاحة للاكتشاف في عُمان', hours: 'تختلف ساعات مقدمي الرعاية', description: 'اكتشف ملفات عيادات الأسنان وأكد الخدمات مباشرة.', tags: ['عيادات', 'مرشحات المناطق', 'ملفات مقدمي الرعاية'] }, { name: 'خدمات العلاج الطبيعي', category: 'فئة خدمة', location: 'متاحة للاكتشاف في عُمان', hours: 'تختلف ساعات مقدمي الرعاية', description: 'استكشف ملفات العلاج الطبيعي دون ادعاءات تصنيف طبي.', tags: ['عافية', 'تواصل مباشر', 'اكتشاف فقط'] }] },
  },
  search: {
    en: { title: 'Search healthcare in Oman', subtitle: 'Search across doctors, clinics, pharmacies, laboratories, services, and health guides with clear local filters.', searchPlaceholder: 'Search doctors, clinics, pharmacies, labs, services, or articles', category: 'Category', language: 'Language', providerType: 'Provider type', specialty: 'Service or specialty', resultsTitle: 'Grouped discovery previews', resultsNote: 'Frontend preview results show the intended search structure before live search data is connected.', relatedTitle: 'Suggested searches', related: ['Doctors in Muscat', 'Clinics in Al Khuwair', 'Pharmacies by area', 'Laboratories in Oman', 'Dental services', 'Health guides'], faqTitle: 'Search FAQ', faqs: [{ q: 'What can I search on DrMuscat?', a: 'The discovery interface is designed for providers, services, locations, and general articles.' }, { q: 'Are results medical recommendations?', a: 'No. Search results are discovery information, not diagnosis or medical advice.' }, { q: 'Can I search by area?', a: 'Yes. Areas update based on the selected city.' }, { q: 'How should I confirm details?', a: 'Contact the provider directly before relying on availability or service details.' }], samples: [{ name: 'Doctor results', category: 'Doctors', location: 'Oman discovery', hours: 'Profile details after approval', description: 'Browse doctor profiles by specialty, city, and area.', tags: ['Specialties', 'Languages', 'Profiles'] }, { name: 'Clinic and center results', category: 'Clinics / Centers', location: 'Oman discovery', hours: 'Confirm directly', description: 'Explore clinics and medical centers using practical local filters.', tags: ['Services', 'Areas', 'Contact actions'] }, { name: 'Articles and guides', category: 'Articles', location: 'Oman healthcare discovery', hours: 'General information only', description: 'Find general guides that do not replace professional medical advice.', tags: ['Health guides', 'Local discovery', 'Not medical advice'] }] },
    ar: { title: 'البحث عن الرعاية الصحية في عُمان', subtitle: 'ابحث بين الأطباء والعيادات والصيدليات والمختبرات والخدمات والأدلة الصحية باستخدام مرشحات محلية واضحة.', searchPlaceholder: 'ابحث عن أطباء أو عيادات أو صيدليات أو مختبرات أو خدمات أو مقالات', category: 'الفئة', language: 'اللغة', providerType: 'نوع مقدم الرعاية', specialty: 'الخدمة أو التخصص', resultsTitle: 'معاينات اكتشاف مجمعة', resultsNote: 'توضح نتائج المعاينة الأمامية هيكل البحث المقصود قبل ربط بيانات البحث المباشرة.', relatedTitle: 'عمليات بحث مقترحة', related: ['أطباء في مسقط', 'عيادات في الخوير', 'صيدليات حسب المنطقة', 'مختبرات في عُمان', 'خدمات الأسنان', 'أدلة صحية'], faqTitle: 'أسئلة البحث', faqs: [{ q: 'ما الذي يمكنني البحث عنه في دكتور مسقط؟', a: 'تم تصميم واجهة الاكتشاف لمقدمي الرعاية والخدمات والمواقع والمقالات العامة.' }, { q: 'هل النتائج توصيات طبية؟', a: 'لا. نتائج البحث معلومات اكتشاف وليست تشخيصاً أو نصيحة طبية.' }, { q: 'هل يمكنني البحث حسب المنطقة؟', a: 'نعم. تتغير المناطق بناءً على المدينة المختارة.' }, { q: 'كيف أؤكد التفاصيل؟', a: 'تواصل مباشرة مع مقدم الرعاية قبل الاعتماد على التوفر أو تفاصيل الخدمة.' }], samples: [{ name: 'نتائج الأطباء', category: 'الأطباء', location: 'اكتشاف عُمان', hours: 'تفاصيل الملف بعد الاعتماد', description: 'تصفح ملفات الأطباء حسب التخصص والمدينة والمنطقة.', tags: ['التخصصات', 'اللغات', 'الملفات'] }, { name: 'نتائج العيادات والمراكز', category: 'العيادات / المراكز', location: 'اكتشاف عُمان', hours: 'أكد مباشرة', description: 'استكشف العيادات والمراكز الطبية باستخدام مرشحات محلية عملية.', tags: ['الخدمات', 'المناطق', 'إجراءات التواصل'] }, { name: 'المقالات والأدلة', category: 'المقالات', location: 'اكتشاف الرعاية في عُمان', hours: 'معلومات عامة فقط', description: 'اعثر على أدلة عامة لا تستبدل النصيحة الطبية المتخصصة.', tags: ['أدلة صحية', 'اكتشاف محلي', 'ليست نصيحة طبية'] }] },
  },
};

export function DiscoveryPage2026({ locale, country, kind, liveContent }: Props) {
  const local = copyByKind[kind][locale];
  const copy = { ...shared[locale], ...local } as Copy;
  const [city, setCity] = useState<string>('Muscat');
  const [area, setArea] = useState<string>('');
  const [notice, setNotice] = useState<string>('');
  const areas = useMemo(() => getAreaOptionsForCity2026(locale, city), [locale, city]);
  const supportUrl = drMuscatSupportWhatsAppUrl(locale);
  const relatedRoutes = [publicDiscoveryRoute(locale, country, 'doctors'), publicDiscoveryRoute(locale, country, 'centers'), publicDiscoveryRoute(locale, country, 'services'), publicArticlesRoute(locale, country)];

  return (
    <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-slate-50/70 text-slate-950">
      <section className="bg-[radial-gradient(circle_at_top_left,rgba(16,185,129,0.2),transparent_40%),linear-gradient(135deg,#052e2b,#0f766e)] px-4 py-14 text-white sm:py-20">
        <div className="mx-auto max-w-7xl"><p className="text-sm font-bold text-emerald-200">{copy.eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight sm:text-5xl">{copy.title}</h1><p className="mt-5 max-w-3xl text-base leading-8 text-emerald-50 sm:text-lg">{copy.subtitle}</p><div className="mt-7 max-w-3xl rounded-2xl bg-white p-2 shadow-xl"><label className="sr-only" htmlFor={`${kind}-search`}>{copy.searchPlaceholder}</label><input id={`${kind}-search`} className="w-full rounded-xl border-0 px-4 py-3 text-base text-slate-950 outline-none placeholder:text-slate-400" placeholder={copy.searchPlaceholder} /></div></div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-10"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-bold">{copy.filtersTitle}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
        <Filter label={copy.country}><select defaultValue="om">{countryOptions2026[locale].map((option) => <option key={option.code} value={option.code} disabled={!option.active}>{option.label}</option>)}</select></Filter>
        <Filter label={copy.city}><select value={city} onChange={(event) => { setCity(event.target.value); setArea(''); }}>{omanCityOptions2026[locale].map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Filter>
        <Filter label={copy.area}><select value={area} onChange={(event) => setArea(event.target.value)}><option value="">{copy.allAreas}</option>{areas.map((option) => <option key={option} value={option}>{option}</option>)}</select></Filter>
        <Filter label={copy.category}><select defaultValue=""><option value="">{copy.allCategories}</option>{copy.samples.map((sample) => <option key={sample.category}>{sample.category}</option>)}</select></Filter>
        <Filter label={copy.specialty}><select defaultValue=""><option value="">{copy.allCategories}</option>{copy.samples.flatMap((sample) => sample.tags.slice(0, 1)).map((tag) => <option key={tag}>{tag}</option>)}</select></Filter>
        <Filter label={copy.sort}><select defaultValue={copy.sorts[0]}>{copy.sorts.map((sort) => <option key={sort}>{sort}</option>)}</select></Filter>
      </div></div></section>

      {liveContent ? <section className="mx-auto max-w-7xl px-4 pb-12"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-5 text-2xl font-bold">{locale === 'ar' ? 'القوائم العامة المعتمدة' : 'Approved public listings'}</h2>{liveContent}</div></section> : null}

      <section className="mx-auto max-w-7xl px-4 pb-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold tracking-tight">{copy.resultsTitle}</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-600">{copy.resultsNote}</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-900">{copy.preview}</span></div><div className="mt-7 grid gap-5 lg:grid-cols-2">{copy.samples.map((sample) => <article key={sample.name} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{sample.category}</p><h3 className="mt-2 text-2xl font-bold">{sample.name}</h3></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{copy.noReviews}</span></div><p className="mt-3 text-sm font-semibold text-slate-600">{sample.location} · {sample.hours}</p><p className="mt-4 text-sm leading-7 text-slate-600">{sample.description}</p><div className="mt-4 flex flex-wrap gap-2">{sample.tags.map((tag) => <span key={tag} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">{tag}</span>)}</div><div className="mt-6 grid gap-2 sm:grid-cols-4"><button type="button" onClick={() => setNotice(copy.actionNotice)} className="rounded-full bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">{copy.view}</button><a href={supportUrl} target="_blank" rel="noreferrer" className="rounded-full bg-green-600 px-4 py-2.5 text-center text-sm font-bold text-white">{copy.whatsapp}</a><button type="button" onClick={() => setNotice(copy.actionNotice)} className="rounded-full border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700">{copy.call}</button><button type="button" onClick={() => setNotice(copy.actionNotice)} className="rounded-full border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700">{copy.directions}</button></div></article>)}</div>{notice ? <p role="status" className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">{notice}</p> : null}</section>

      <section className="mx-auto grid max-w-7xl gap-6 px-4 pb-12 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">{copy.mapTitle}</h2><div className="mt-5 flex min-h-52 items-center justify-center rounded-2xl border border-dashed border-emerald-300 bg-emerald-50 p-6 text-center text-sm leading-7 text-emerald-900">{copy.mapBody}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">{copy.relatedTitle}</h2><div className="mt-5 flex flex-wrap gap-3">{copy.related.map((item, index) => <Link key={item} href={relatedRoutes[index % relatedRoutes.length]!} className="rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-900">{item}</Link>)}</div><Link href={publicProviderRoute(locale, country)} className="mt-6 inline-flex rounded-full bg-emerald-800 px-5 py-3 text-sm font-bold text-white">{locale === 'ar' ? 'طلب إدراج مقدم رعاية' : 'Request provider listing'}</Link></div></section>

      <section className="mx-auto max-w-7xl px-4 pb-12"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-3xl font-bold">{copy.faqTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{copy.faqs.map((faq) => <details key={faq.q} className="rounded-2xl border border-slate-200 p-4"><summary className="cursor-pointer font-bold">{faq.q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{faq.a}</p></details>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-4 pb-16"><div className="rounded-3xl bg-slate-900 p-6 text-white sm:p-8"><h2 className="text-2xl font-bold">{copy.safetyTitle}</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-200">{copy.safety}</p></div></section>
    </main>
  );
}

function Filter({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="text-sm font-bold text-slate-700">{label}<span className="mt-2 block [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:px-3 [&_select]:py-3 [&_select]:text-sm [&_select]:font-medium [&_select]:text-slate-800 [&_select]:outline-none [&_select]:focus:border-emerald-500">{children}</span></label>;
}
